services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 2s
      interval: 5s
      retries: 10

  migrations:
    build:
      context: .
      dockerfile: migrations.dockerfile
    depends_on:
      mysql:
        condition: service_healthy

  oncall:
    build:
      context: .
      dockerfile: oncall.dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - migrations

volumes:
  mysql-data:
